# Generated by Django 4.0.4 on 2022-05-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0002_articlesmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesmodel',
            old_name='time_created',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='articlesmodel',
            old_name='time_updated',
            new_name='time_update',
        ),
    ]
