# Generated by Django 4.0.4 on 2022-05-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0003_rename_time_created_articlesmodel_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
