# Generated by Django 4.0.4 on 2022-05-04 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articlesapp', '0004_alter_articlesmodel_content_alter_articlesmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesmodel',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlesmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
