# Generated by Django 4.0.4 on 2022-05-04 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articlesapp', '0006_remove_articlesmodel_liked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesrelationmodel',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='articlesrelationmodel',
            name='like',
        ),
        migrations.CreateModel(
            name='ArticlesCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesapp.articlesmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
