# Generated by Django 4.0.4 on 2022-05-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0008_rename_articlesrelationmodel_articleslikesmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesCommentsModel',
        ),
    ]
