# Generated by Django 4.0.4 on 2022-05-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesapp', '0010_articlescommentsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticlesCommentsModel',
        ),
    ]
